from __future__ import annotations

GUIDES_TAB = "GUIDES"
ACHIEVEMENTS_TAB = "SUCCÈS"
QUESTS_TAB = "QUÊTES"
DUNGEONS_TAB = "DONJONS"
MONSTERS_TAB = "MONSTRES"
ARCHMONSTERS_TAB = "ARCHIMONSTRES"
WANTED_TAB = "AVIS DE RECHERCHE"

ENCYCLOPEDIA_TABS: tuple[str, ...] = (
    GUIDES_TAB,
    QUESTS_TAB,
    ACHIEVEMENTS_TAB,
    DUNGEONS_TAB,
    MONSTERS_TAB,
    ARCHMONSTERS_TAB,
    WANTED_TAB,
)

DEFAULT_TAB = QUESTS_TAB
