"""Lazy public facade for the network package.

Importing a submodule such as the elevated capture helper must not hydrate
the calibration, progression, UI, or raw-capture stacks. Public imports from
``app.network`` remain compatible and resolve only when first requested.
"""

from __future__ import annotations

from importlib import import_module


_LAZY_EXPORTS = {
    "AchievementCompletedEvent": ("app.network.events", "AchievementCompletedEvent"),
    "AchievementObjectiveCompletedEvent": ("app.network.events", "AchievementObjectiveCompletedEvent"),
    "ActiveProtocolBuildFingerprintProvider": ("app.network.build_fingerprint", "ActiveProtocolBuildFingerprintProvider"),
    "BusinessNetworkEvent": ("app.network.events", "BusinessNetworkEvent"),
    "CapturedProtocolMessage": ("app.network.transport", "CapturedProtocolMessage"),
    "CharacterIdentifiedEvent": ("app.network.events", "CharacterIdentifiedEvent"),
    "CharacterResolution": ("app.network.character_resolver", "CharacterResolution"),
    "CharacterSlotResolver": ("app.network.character_resolver", "CharacterSlotResolver"),
    "CorrelatedCharacterIdentityDecoder": ("app.network.correlated_identity_decoder", "CorrelatedCharacterIdentityDecoder"),
    "CorrelatedCharacterIdentityRule": ("app.network.correlated_identity_decoder", "CorrelatedCharacterIdentityRule"),
    "CurrentProtocolCalibration": ("app.network.protocol_calibration", "CurrentProtocolCalibration"),
    "DEFAULT_PROTOCOL_EXTRACT_ROOT": ("app.network.protocol_extract", "DEFAULT_PROTOCOL_EXTRACT_ROOT"),
    "DEFAULT_PROTOCOL_MAPPING_DIR": ("app.network.contracts", "DEFAULT_PROTOCOL_MAPPING_DIR"),
    "DEFAULT_REQUIRED_SEMANTICS": ("app.network.readiness_audit", "DEFAULT_REQUIRED_SEMANTICS"),
    "DOFUS_361010_PROFILE": ("app.network.current_protocol_profile", "DOFUS_361010_PROFILE"),
    "DecodedClientMessage": ("app.network.normalizer", "DecodedClientMessage"),
    "DecodedNetworkEventSource": ("app.network.transport", "DecodedNetworkEventSource"),
    "DeobfuscationEvidenceBundle": ("app.network.deobfs_bundle", "DeobfuscationEvidenceBundle"),
    "DeobfuscationEvidenceBundleError": ("app.network.deobfs_bundle", "DeobfuscationEvidenceBundleError"),
    "DeobfuscationEvidenceValidation": ("app.network.deobfs_audit", "DeobfuscationEvidenceValidation"),
    "DeobfuscationMatch": ("app.network.deobfs_report", "DeobfuscationMatch"),
    "DeobfuscationReport": ("app.network.deobfs_report", "DeobfuscationReport"),
    "DeobfuscationReportDigest": ("app.network.deobfs_bundle", "DeobfuscationReportDigest"),
    "DeobfuscationReportError": ("app.network.deobfs_report", "DeobfuscationReportError"),
    "DiscoveryEvidenceCandidate": ("app.network.discovery_evidence", "DiscoveryEvidenceCandidate"),
    "EventApplicationResult": ("app.network.progress_bridge", "EventApplicationResult"),
    "FinishedQuestsSnapshotDecoder": ("app.network.quest_snapshot_decoder", "FinishedQuestsSnapshotDecoder"),
    "FinishedQuestsSnapshotEvent": ("app.network.events", "FinishedQuestsSnapshotEvent"),
    "FinishedQuestsSnapshotRule": ("app.network.quest_snapshot_decoder", "FinishedQuestsSnapshotRule"),
    "Fixed32Value": ("app.network.protobuf_fields", "Fixed32Value"),
    "Fixed64Value": ("app.network.protobuf_fields", "Fixed64Value"),
    "FramedProtocolMessage": ("app.network.wire", "FramedProtocolMessage"),
    "LocalProtocolStatus": ("app.network.protocol_status", "LocalProtocolStatus"),
    "MappingEvidenceValidation": ("app.network.mapping_evidence", "MappingEvidenceValidation"),
    "NetworkApplicationCoordinator": ("app.network.application_coordinator", "NetworkApplicationCoordinator"),
    "NetworkApplicationStatus": ("app.network.application_coordinator", "NetworkApplicationStatus"),
    "NetworkBootstrapResult": ("app.network.bootstrap", "NetworkBootstrapResult"),
    "NetworkControllerStatus": ("app.network.controller", "NetworkControllerStatus"),
    "NetworkEvent": ("app.network.events", "NetworkEvent"),
    "NetworkEventRuntime": ("app.network.runtime", "NetworkEventRuntime"),
    "NetworkEventSource": ("app.network.source", "NetworkEventSource"),
    "NetworkProgressBridge": ("app.network.progress_bridge", "NetworkProgressBridge"),
    "NetworkRuntimeContext": ("app.network.controller", "NetworkRuntimeContext"),
    "NetworkRuntimeController": ("app.network.controller", "NetworkRuntimeController"),
    "ParsedIpv4TcpPacket": ("app.network.windows_capture", "ParsedIpv4TcpPacket"),
    "ProtobufAnyStreamDecoder": ("app.network.wire", "ProtobufAnyStreamDecoder"),
    "ProtobufDecodeError": ("app.network.protobuf_fields", "ProtobufDecodeError"),
    "ProtocolBuildFiles": ("app.network.build_fingerprint", "ProtocolBuildFiles"),
    "ProtocolCalibrationBootstrapResult": ("app.network.calibration_bootstrap", "ProtocolCalibrationBootstrapResult"),
    "ProtocolCalibrationCertificate": ("app.network.protocol_calibration", "ProtocolCalibrationCertificate"),
    "ProtocolCalibrationController": ("app.network.calibration_controller", "ProtocolCalibrationController"),
    "ProtocolCalibrationControllerStatus": ("app.network.calibration_controller", "ProtocolCalibrationControllerStatus"),
    "ProtocolCalibrationRuntime": ("app.network.calibration_runtime", "ProtocolCalibrationRuntime"),
    "ProtocolCalibrationStatus": ("app.network.protocol_calibration", "ProtocolCalibrationStatus"),
    "ProtocolDiagnosticsCollector": ("app.network.diagnostics", "ProtocolDiagnosticsCollector"),
    "ProtocolDiscoveryConsensus": ("app.network.discovery_evidence", "ProtocolDiscoveryConsensus"),
    "ProtocolDiscoveryEvidenceError": ("app.network.discovery_evidence", "ProtocolDiscoveryEvidenceError"),
    "ProtocolEventNormalizer": ("app.network.normalizer", "ProtocolEventNormalizer"),
    "ProtocolExtractionError": ("app.network.protocol_extract", "ProtocolExtractionError"),
    "ProtocolExtractionResult": ("app.network.protocol_extract", "ProtocolExtractionResult"),
    "ProtocolFieldCandidate": ("app.network.discovery", "ProtocolFieldCandidate"),
    "ProtocolFieldRule": ("app.network.mapped_decoder", "ProtocolFieldRule"),
    "ProtocolMappingError": ("app.network.mapping_manifest", "ProtocolMappingError"),
    "ProtocolMappingInstallResult": ("app.network.mapping_install", "ProtocolMappingInstallResult"),
    "ProtocolMappingManifest": ("app.network.mapping_manifest", "ProtocolMappingManifest"),
    "ProtocolMappingReadinessValidation": ("app.network.readiness_audit", "ProtocolMappingReadinessValidation"),
    "ProtocolMappingRegistry": ("app.network.mapping_registry", "ProtocolMappingRegistry"),
    "ProtocolMappingSelection": ("app.network.mapping_registry", "ProtocolMappingSelection"),
    "ProtocolMessageDecoder": ("app.network.transport", "ProtocolMessageDecoder"),
    "ProtocolMessageRule": ("app.network.mapped_decoder", "ProtocolMessageRule"),
    "ProtocolMessageSource": ("app.network.transport", "ProtocolMessageSource"),
    "ProtocolTargetDiscoveryCollector": ("app.network.discovery", "ProtocolTargetDiscoveryCollector"),
    "ProtocolTransportItem": ("app.network.transport", "ProtocolTransportItem"),
    "ProtocolTypeDiagnostic": ("app.network.diagnostics", "ProtocolTypeDiagnostic"),
    "QuestCompletedEvent": ("app.network.events", "QuestCompletedEvent"),
    "QuestCompletionInfoDecoder": ("app.network.quest_completion_info_decoder", "QuestCompletionInfoDecoder"),
    "QuestCompletionInfoRule": ("app.network.quest_completion_info_decoder", "QuestCompletionInfoRule"),
    "QuestObjectiveCompletedEvent": ("app.network.events", "QuestObjectiveCompletedEvent"),
    "QuestStartedEvent": ("app.network.events", "QuestStartedEvent"),
    "REQUIRED_RUNTIME_EVENTS": ("app.network.contracts", "REQUIRED_RUNTIME_EVENTS"),
    "REQUIRED_RUNTIME_SEMANTICS": ("app.network.contracts", "REQUIRED_RUNTIME_SEMANTICS"),
    "ReviewedProtocolProfile": ("app.network.current_protocol_profile", "ReviewedProtocolProfile"),
    "SessionClosedEvent": ("app.network.events", "SessionClosedEvent"),
    "StrictMappedProtocolDecoder": ("app.network.mapped_decoder", "StrictMappedProtocolDecoder"),
    "TcpStreamReassembler": ("app.network.wire", "TcpStreamReassembler"),
    "TransportSessionClosed": ("app.network.transport", "TransportSessionClosed"),
    "WindowsRawProtocolSource": ("app.network.windows_capture", "WindowsRawProtocolSource"),
    "WindowsTcpFlow": ("app.network.windows_tcp", "WindowsTcpFlow"),
    "ankama_type_alias": ("app.network.deobfs_report", "ankama_type_alias"),
    "audit_protocol_mapping_readiness": ("app.network.readiness_audit", "audit_protocol_mapping_readiness"),
    "build_discovery_consensus": ("app.network.discovery_evidence", "build_discovery_consensus"),
    "build_windows_network_runtime": ("app.network.bootstrap", "build_windows_network_runtime"),
    "build_windows_protocol_calibration": ("app.network.calibration_bootstrap", "build_windows_protocol_calibration"),
    "create_deobfuscation_evidence_bundle": ("app.network.deobfs_bundle", "create_deobfuscation_evidence_bundle"),
    "dofus_361010_candidate_manifest": ("app.network.current_protocol_profile", "dofus_361010_candidate_manifest"),
    "dofus_361010_candidate_mapping_payload": ("app.network.current_protocol_profile", "dofus_361010_candidate_mapping_payload"),
    "dofus_361010_profile_digest": ("app.network.current_protocol_profile", "dofus_361010_profile_digest"),
    "established_tcp_flows_for_pids": ("app.network.windows_tcp", "established_tcp_flows_for_pids"),
    "extract_protocol_from_build": ("app.network.protocol_extract", "extract_protocol_from_build"),
    "inspect_local_protocol_status": ("app.network.protocol_status", "inspect_local_protocol_status"),
    "install_calibrated_current_profile": ("app.network.calibrated_mapping_install", "install_calibrated_current_profile"),
    "install_verified_protocol_mapping": ("app.network.mapping_install", "install_verified_protocol_mapping"),
    "load_deobfuscation_evidence_bundle": ("app.network.deobfs_bundle", "load_deobfuscation_evidence_bundle"),
    "load_deobfuscation_report": ("app.network.deobfs_report", "load_deobfuscation_report"),
    "load_protocol_mapping": ("app.network.mapping_manifest", "load_protocol_mapping"),
    "missing_runtime_capabilities": ("app.network.contracts", "missing_runtime_capabilities"),
    "parse_deobfuscation_evidence_bundle": ("app.network.deobfs_bundle", "parse_deobfuscation_evidence_bundle"),
    "parse_deobfuscation_report": ("app.network.deobfs_report", "parse_deobfuscation_report"),
    "parse_discovery_consensus": ("app.network.discovery_evidence", "parse_discovery_consensus"),
    "parse_ipv4_tcp_packet": ("app.network.windows_capture", "parse_ipv4_tcp_packet"),
    "parse_protobuf_fields": ("app.network.protobuf_fields", "parse_protobuf_fields"),
    "parse_protocol_mapping": ("app.network.mapping_manifest", "parse_protocol_mapping"),
    "process_executable_path": ("app.network.build_fingerprint", "process_executable_path"),
    "protocol_build_files_for_executable": ("app.network.build_fingerprint", "protocol_build_files_for_executable"),
    "protocol_build_sha256": ("app.network.build_fingerprint", "protocol_build_sha256"),
    "resolve_active_protocol_build": ("app.network.protocol_extract", "resolve_active_protocol_build"),
    "resolve_field_path": ("app.network.protobuf_fields", "resolve_field_path"),
    "runtime_capabilities_ready": ("app.network.contracts", "runtime_capabilities_ready"),
    "validate_consensus_deobfuscation": ("app.network.deobfs_audit", "validate_consensus_deobfuscation"),
    "validate_consensus_deobfuscation_reports": ("app.network.deobfs_audit", "validate_consensus_deobfuscation_reports"),
    "validate_mapping_against_consensus": ("app.network.mapping_evidence", "validate_mapping_against_consensus"),
    "validate_protocol_mapping_readiness": ("app.network.readiness_audit", "validate_protocol_mapping_readiness"),
    "verify_deobfuscation_evidence_bundle": ("app.network.deobfs_bundle", "verify_deobfuscation_evidence_bundle"),
}


_LAZY_SUBMODULES = {
    "application_coordinator": "app.network.application_coordinator",
    "bootstrap": "app.network.bootstrap",
    "build_fingerprint": "app.network.build_fingerprint",
    "calibrated_mapping_install": "app.network.calibrated_mapping_install",
    "calibration_bootstrap": "app.network.calibration_bootstrap",
    "calibration_controller": "app.network.calibration_controller",
    "calibration_runtime": "app.network.calibration_runtime",
    "character_resolver": "app.network.character_resolver",
    "contracts": "app.network.contracts",
    "controller": "app.network.controller",
    "correlated_identity_decoder": "app.network.correlated_identity_decoder",
    "current_protocol_profile": "app.network.current_protocol_profile",
    "deobfs_audit": "app.network.deobfs_audit",
    "deobfs_bundle": "app.network.deobfs_bundle",
    "deobfs_report": "app.network.deobfs_report",
    "diagnostics": "app.network.diagnostics",
    "discovery": "app.network.discovery",
    "discovery_evidence": "app.network.discovery_evidence",
    "events": "app.network.events",
    "mapped_decoder": "app.network.mapped_decoder",
    "mapping_evidence": "app.network.mapping_evidence",
    "mapping_install": "app.network.mapping_install",
    "mapping_manifest": "app.network.mapping_manifest",
    "mapping_registry": "app.network.mapping_registry",
    "normalizer": "app.network.normalizer",
    "progress_bridge": "app.network.progress_bridge",
    "protobuf_fields": "app.network.protobuf_fields",
    "protocol_calibration": "app.network.protocol_calibration",
    "protocol_extract": "app.network.protocol_extract",
    "protocol_status": "app.network.protocol_status",
    "quest_completion_info_decoder": "app.network.quest_completion_info_decoder",
    "quest_snapshot_decoder": "app.network.quest_snapshot_decoder",
    "readiness_audit": "app.network.readiness_audit",
    "runtime": "app.network.runtime",
    "source": "app.network.source",
    "transport": "app.network.transport",
    "windows_capture": "app.network.windows_capture",
    "windows_tcp": "app.network.windows_tcp",
    "wire": "app.network.wire",
}


def __getattr__(name: str):
    export = _LAZY_EXPORTS.get(name)
    if export is not None:
        module_name, attribute_name = export
        value = getattr(import_module(module_name), attribute_name)
    else:
        module_name = _LAZY_SUBMODULES.get(name)
        if module_name is None:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
        value = import_module(module_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__) | set(_LAZY_SUBMODULES))


__all__ = [
    "AchievementCompletedEvent",
    "AchievementObjectiveCompletedEvent",
    "ActiveProtocolBuildFingerprintProvider",
    "BusinessNetworkEvent",
    "CapturedProtocolMessage",
    "CharacterIdentifiedEvent",
    "CharacterResolution",
    "CharacterSlotResolver",
    "CorrelatedCharacterIdentityDecoder",
    "CorrelatedCharacterIdentityRule",
    "CurrentProtocolCalibration",
    "DEFAULT_PROTOCOL_EXTRACT_ROOT",
    "DEFAULT_PROTOCOL_MAPPING_DIR",
    "DEFAULT_REQUIRED_SEMANTICS",
    "DOFUS_361010_PROFILE",
    "DecodedClientMessage",
    "DecodedNetworkEventSource",
    "DeobfuscationEvidenceBundle",
    "DeobfuscationEvidenceBundleError",
    "DeobfuscationEvidenceValidation",
    "DeobfuscationMatch",
    "DeobfuscationReport",
    "DeobfuscationReportDigest",
    "DeobfuscationReportError",
    "DiscoveryEvidenceCandidate",
    "EventApplicationResult",
    "FinishedQuestsSnapshotDecoder",
    "FinishedQuestsSnapshotEvent",
    "FinishedQuestsSnapshotRule",
    "Fixed32Value",
    "Fixed64Value",
    "FramedProtocolMessage",
    "LocalProtocolStatus",
    "MappingEvidenceValidation",
    "NetworkApplicationCoordinator",
    "NetworkApplicationStatus",
    "NetworkBootstrapResult",
    "NetworkControllerStatus",
    "NetworkEvent",
    "NetworkEventRuntime",
    "NetworkEventSource",
    "NetworkProgressBridge",
    "NetworkRuntimeContext",
    "NetworkRuntimeController",
    "ParsedIpv4TcpPacket",
    "ProtocolBuildFiles",
    "ProtocolCalibrationBootstrapResult",
    "ProtocolCalibrationCertificate",
    "ProtocolCalibrationController",
    "ProtocolCalibrationControllerStatus",
    "ProtocolCalibrationRuntime",
    "ProtocolCalibrationStatus",
    "ProtocolDiagnosticsCollector",
    "ProtocolDiscoveryConsensus",
    "ProtocolDiscoveryEvidenceError",
    "ProtocolEventNormalizer",
    "ProtocolExtractionError",
    "ProtocolExtractionResult",
    "ProtocolFieldCandidate",
    "ProtocolFieldRule",
    "ProtocolMappingError",
    "ProtocolMappingInstallResult",
    "ProtocolMappingManifest",
    "ProtocolMappingReadinessValidation",
    "ProtocolMappingRegistry",
    "ProtocolMappingSelection",
    "ProtocolMessageDecoder",
    "ProtocolMessageRule",
    "ProtocolMessageSource",
    "ProtocolTargetDiscoveryCollector",
    "ProtocolTransportItem",
    "ProtocolTypeDiagnostic",
    "ProtobufAnyStreamDecoder",
    "ProtobufDecodeError",
    "QuestCompletedEvent",
    "QuestCompletionInfoDecoder",
    "QuestCompletionInfoRule",
    "QuestObjectiveCompletedEvent",
    "QuestStartedEvent",
    "REQUIRED_RUNTIME_EVENTS",
    "REQUIRED_RUNTIME_SEMANTICS",
    "ReviewedProtocolProfile",
    "SessionClosedEvent",
    "StrictMappedProtocolDecoder",
    "TcpStreamReassembler",
    "TransportSessionClosed",
    "WindowsRawProtocolSource",
    "WindowsTcpFlow",
    "ankama_type_alias",
    "audit_protocol_mapping_readiness",
    "build_discovery_consensus",
    "build_windows_network_runtime",
    "build_windows_protocol_calibration",
    "create_deobfuscation_evidence_bundle",
    "dofus_361010_candidate_manifest",
    "dofus_361010_candidate_mapping_payload",
    "dofus_361010_profile_digest",
    "established_tcp_flows_for_pids",
    "extract_protocol_from_build",
    "inspect_local_protocol_status",
    "install_calibrated_current_profile",
    "install_verified_protocol_mapping",
    "load_deobfuscation_evidence_bundle",
    "load_deobfuscation_report",
    "load_protocol_mapping",
    "missing_runtime_capabilities",
    "parse_deobfuscation_evidence_bundle",
    "parse_deobfuscation_report",
    "parse_discovery_consensus",
    "parse_ipv4_tcp_packet",
    "parse_protobuf_fields",
    "parse_protocol_mapping",
    "process_executable_path",
    "protocol_build_files_for_executable",
    "protocol_build_sha256",
    "resolve_active_protocol_build",
    "resolve_field_path",
    "runtime_capabilities_ready",
    "validate_consensus_deobfuscation",
    "validate_consensus_deobfuscation_reports",
    "validate_mapping_against_consensus",
    "validate_protocol_mapping_readiness",
    "verify_deobfuscation_evidence_bundle",
]
